package com.demo.model;

import io.jboot.db.annotation.Table;
import com.demo.model.base.BaseFiles;

/**
 * Generated by Jboot.
 */
@Table(tableName = "files", primaryKey = "id")
public class Files extends BaseFiles<Files> {
	private Long id;

	private String fileName;

	private Long fileSize;

	private String fileType;

	private Boolean fileStatus;

	//调用父类的set方法，写入数据库时使用
	public  void  toSet(){
		super.setFileName(fileName);
		super.setFileSize(fileSize);
		super.setFileType(fileType);
		super.setFileStatus(fileStatus);
	}

	@Override
	public String toString() {
		return "Files{" +
				"id=" + id +
				", fileName='" + fileName + '\'' +
				", fileSize=" + fileSize +
				", fileType='" + fileType + '\'' +
				", fileStatus=" + fileStatus +
				'}';
	}
}
