package com.demo.model;

import io.jboot.db.annotation.Table;
import com.demo.model.base.BaseFiles;

/**
 * Generated by Jboot.
 */
/**
 * @className Files
 * @description 文件实体类
 * @author yh128
 * @createTime 2019/6/11 15:39
 */
@Table(tableName = "files", primaryKey = "id")
public class Files extends BaseFiles<Files> {
	
}
