package com.demo.model;

import io.jboot.db.annotation.Table;
import com.demo.model.base.BaseRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "role", primaryKey = "id")
public class Role extends BaseRole<Role> {
	
}
