package com.demo.model;

import io.jboot.db.annotation.Table;
import com.demo.model.base.BaseSysData;

/**
 * Generated by Jboot.
 */
/**
 * @className SysData
 * @description 系统数据实体类
 * @author yh128
 * @createTime 2019/6/11 15:40
 */
@Table(tableName = "sys_data", primaryKey = "id")
public class SysData extends BaseSysData<SysData> {
	
}
