package com.demo.model;

import io.jboot.db.annotation.Table;
import com.demo.model.base.BaseSysType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_type", primaryKey = "id")
public class SysType extends BaseSysType<SysType> {
	
}
