package com.demo.model;

import io.jboot.db.annotation.Table;
import com.demo.model.base.BaseUser;

/**
 * Generated by Jboot.
 */
/**
 * @className User
 * @description 用户实体类
 * @author yh128
 * @createTime 2019/6/11 15:40
 */
@Table(tableName = "user", primaryKey = "id")
public class User extends BaseUser<User> {
	
}
