package com.demo.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
/**
 * @className BaseSysData
 * @description 系统数据基础类
 * @author yh128
 * @createTime 2019/6/11 15:38
 */
public abstract class BaseSysData<M extends BaseSysData<M>> extends JbootModel<M> implements IBean {

    public void setId(java.lang.Long id) {
        set("id", id);
    }

    public java.lang.Long getId() {
        return getLong("id");
    }

    public void setSysName(java.lang.String sysName) {
        set("sys_name", sysName);
    }

    public java.lang.String getSysName() {
        return getStr("sys_name");
    }

    public void setSysKey(java.lang.String sysKey) {
        set("sys_key", sysKey);
    }

    public java.lang.String getSysKey() {
        return getStr("sys_key");
    }

    public void setSysValue(java.lang.String sysValue) {
        set("sys_value", sysValue);
    }

    public java.lang.String getSysValue() {
        return getStr("sys_value");
    }

}
