package com.demo.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
/**
 * @className BaseFiles
 * @description 文件基础类
 * @author yh128
 * @createTime 2019/6/11 15:38
 */
public abstract class BaseFiles<M extends BaseFiles<M>> extends JbootModel<M> implements IBean {

    public void setId(java.lang.Long id) {
        set("id", id);
    }

    public java.lang.Long getId() {
        return getLong("id");
    }

    public void setFileName(java.lang.String fileName) {
        set("file_name", fileName);
    }

    public java.lang.String getFileName() {
        return getStr("file_name");
    }

    public void setFileSize(java.lang.Long fileSize) {
        set("file_size", fileSize);
    }

    public java.lang.Long getFileSize() {
        return getLong("file_size");
    }

    public void setFileType(java.lang.String fileType) {
        set("file_type", fileType);
    }

    public java.lang.String getFileType() {
        return getStr("file_type");
    }

    public void setFileStatus(java.lang.Integer fileStatus) {
        set("file_status", fileStatus);
    }

    public java.lang.Integer getFileStatus() {
        return getInt("file_status");
    }

}
