package com.demo.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
/**
 * @className BaseUser
 * @description 用户基础类
 * @author yh128
 * @createTime 2019/6/11 15:38
 */
public abstract class BaseUser<M extends BaseUser<M>> extends JbootModel<M> implements IBean {

    public void setId(java.lang.Long id) {
        set("id", id);
    }

    public java.lang.Long getId() {
        return getLong("id");
    }

    public void setRealName(java.lang.String realName) {
        set("real_name", realName);
    }

    public java.lang.String getRealName() {
        return getStr("real_name");
    }

    public void setAddress(java.lang.String address) {
        set("address", address);
    }

    public java.lang.String getAddress() {
        return getStr("address");
    }

    public void setMobile(java.lang.String mobile) {
        set("mobile", mobile);
    }

    public java.lang.String getMobile() {
        return getStr("mobile");
    }

    public void setSex(java.lang.Integer sex) {
        set("sex", sex);
    }

    public java.lang.Integer getSex() {
        return getInt("sex");
    }

    public void setAge(java.lang.Integer age) {
        set("age", age);
    }

    public java.lang.Integer getAge() {
        return getInt("age");
    }

    public void setLoginName(java.lang.String loginName) {
        set("login_name", loginName);
    }

    public java.lang.String getLoginName() {
        return getStr("login_name");
    }

    public void setPassword(java.lang.String password) {
        set("password", password);
    }

    public java.lang.String getPassword() {
        return getStr("password");
    }

}
