package com.demo.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysType<M extends BaseSysType<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setTypeName(java.lang.String typeName) {
		set("type_name", typeName);
	}
	
	public java.lang.String getTypeName() {
		return getStr("type_name");
	}

	public void setTypeValue(java.lang.String typeValue) {
		set("type_value", typeValue);
	}
	
	public java.lang.String getTypeValue() {
		return getStr("type_value");
	}

	public void setTypeStaus(java.lang.Boolean typeStaus) {
		set("type_staus", typeStaus);
	}
	
	public java.lang.Boolean getTypeStaus() {
		return get("type_staus");
	}

}
